Booster to dto
osipaandr/pojo-booster pull request #1
Opened 2020-03-10 16:57 UTC by osipaandr

2020-03-10 17:50 UTC, VladBytsyuk requested changes

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +        val classes = (psiFile as PsiJavaFile).classes
```as``` может вызвать ClassCastException. 
Ты точно уверен, что тут не может быть ничего, кроме ```PsiJavaFile```?

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +        WriteCommandAction.runWriteCommandAction(project) {
Однострочные лямбды обычно пишутся в одну строку с функцией. Разделяют, если тело лямбды большое.

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +            (pid != null) -> pid
Почему условия в скобках? Зачем они тут нужны?

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +                }
Эта конструкция очень тяжело читается. Тут лучше выделить переменную ```decapitalizedName```, а потом делать вызовы ```findField(...)```

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +                }
А вообще, я бы вынес переменную ```decapitalizedName``` за ```when```, и обрабатывал nullability уже в ветках ```when```

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/todto/BoostToDtoAction.kt
> +        }
Тут ситуация получше, но я бы разбил на:
```
val psiFile = event.getData(PlatformDataKeys.PSI_FILE)
psiFile?.let { BoosterToDto(event).boost(it) }
```

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/todto/BoosterToDto.kt
> +        }
Аналогично избавился бы от ```let``` здесь. 
Например, в 43 строке, ```let``` более читаем, чем здесь, потому что все выражение короче и его легче держать в уме.
```
psiClass.findIdField()?.let { psiClass.putFirst(it) }
```

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/toentity/BoostToEntityAction.kt
> +        }
Аналогично с классом ```BoostToDtoAction```. Даже первоначальный вариант кажется лучше текущего. (Но в первоначальном стоило бы перенести ```?: return``` на новую строку, чтобы точки выхода из функции были визуально заметнее).

2020-03-10 17:50 UTC, VladBytsyuk commented on src/main/kotlin/todto/BoosterToDto.kt
> +    }
Дублирование. Это анонимная реализация, но она повторяется в обоих наследниках ```AbstractPojoBooster```. Это стоит выделить в именнованную реализацию  в отдельное место или же сделать частью ```AbstractPojoBooster```.

2020-03-10 18:30 UTC, osipaandr commented on src/main/kotlin/todto/BoosterToDto.kt
> +    }
тут вообще отдельная песня. Переделал

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/toentity/BoostToEntityAction.kt
> +        }
исправил

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/todto/BoosterToDto.kt
> +        }
готово

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/todto/BoostToDtoAction.kt
> +        }
готово

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/AbstractPojoBooster.kt
> +                }
Остановился на 1 варианте

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/AbstractPojoBooster.kt
> +            (pid != null) -> pid
убрал

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/AbstractPojoBooster.kt
> +        WriteCommandAction.runWriteCommandAction(project) {
исправил

2020-03-10 18:31 UTC, osipaandr commented on src/main/kotlin/AbstractPojoBooster.kt
> +        val classes = (psiFile as PsiJavaFile).classes
Добавил todo. Позже сделаю возможность применения этих Action только для Java-файлов

2020-03-11 09:42 UTC, VladBytsyuk requested changes

2020-03-11 09:42 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +    }
Тут 3 проблемы:
1. Функция сразу возвращает значение, а значит не нужны ни фигурные скобки, ни ```return```. Надо заменить на ```=```
2. Логическое выражение странно разбито на строки. Тут кажется логичней разбить так
```
(name.startsWith("get") || name.startsWith("set"))
 && null != containingClass?.findFieldByName(name.substring(ACCESSOR_PREFIX_LENGTH).decapitalize(), true)
```
3. В Kotlin обычно переносят аргументы функции несколько иначе чем в Java. 
Например, если аргументы не влезают на одну строку с именем функции, закрывающая скобка должны быть на новой строке. 
```
containingClass?.findFieldByName(
    name.substring(ACCESSOR_PREFIX_LENGTH).decapitalize(), true
)
```
Включи в настройках IDEA стайлгайд котлина, и он тебе такие моменты будет подказывать.

2020-03-11 09:42 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +    }
Еще на самом деле это не особо имеет смысл выделять в функцию. 
Тут можно использовать ```val``` геттер.
```
protected val PsiMethod.isAccessor: Boolean get {...}
```

2020-03-11 09:42 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +    }
И еще странно выглядит следующая проверка ```null != smth```. Обычно все таки проверяют, что что-либо не равно null, а не наоборот

2020-03-11 09:42 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +        }
Тут чистая вкусовщина, но я бы убрал скобки и перенес ```delete()``` на строку к ```if```. Мне кажется, что так легче читается.

2020-03-11 09:42 UTC, VladBytsyuk commented on src/main/kotlin/todto/BoosterToDto.kt
> +            }
Все равно когнитивно тяжело понимать этот кусок. Можно сделать так
```
modifiers ?: return
if (!modifiers.hasAnnotation(jsonIgnore)) {
    modifiers.addAnnotationIfNecessary(jsonProperty(field.name))
}
```
Я бы не рекомендовал оставлять имя ```it``` для любой лямбды больше чем в одну строку. А в данном случае простое именование аргумента лямбды не особо спасет.
Плюс -  в таком подходе уменьшается вложенность кода.

2020-03-11 21:27 UTC, osipaandr commented on src/main/kotlin/AbstractPojoBooster.kt
> +    }
по пункту сделал чуть другие переносы, потому что идее не нравится начинать строку с `&&`

2020-03-13 07:01 UTC, VladBytsyuk commented on src/main/kotlin/AbstractPojoBooster.kt
> +    }
Вообще начинать строку с ```&&``` и ```||``` это хорошая практика. Ты всегда можешь увидеть сразу выбранную операцию, и не должен искать глазами конец строки. Ну ок.

2020-03-13 07:01 UTC, merged